### ISSUE TITLE
Update the Android Gradle plugin

### ISSUE THREAD

**Issue by chepsi** [droidconKE/droidconKE2023Android#123]
Currently, we are using Android Gradle Plugin Version 7.4.1 we'd like to [update](https://developer.android.com/build/releases/gradle-plugin#updating-plugin) to the latest version. Please test thoroughly that the app works after the update.

**Comment by wangerekaharun** [comment]
@chepsi This needs everyone to be on Java 17 - due to the requirement of AGP Plugin v. 8.0.0. There's a workaround though. I have the changes ready if we can use the workaround - basically setting the gradle java home version to use the Android Studio Java Version in the Global` gradle.properties` file

**Comment by wangerekaharun** [comment]
> @wangerekaharun Sounds good. Can we add information about this in the readme with the corresponding PR once ready?

I will add that

**Comment by wangerekaharun** [comment]
@chepsi the PR for this is up
